src/Entity/PlanesCategory.php
<?php

namespace App\Entity;

use App\Repository\PlanesCategoryRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlanesCategoryRepository::class)]
class PlanesCategory
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?bool $active = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\OneToMany(mappedBy: 'category', targetEntity: Plane::class)]
    private Collection $planes;

    #[ORM\Column(length: 255)]
    private ?string $image = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $hero_img = null;

    public function __construct()
    {
        $this->planes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function isActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return Collection<int, Plane>
     */
    public function getPlanes(): Collection
    {
        return $this->planes;
    }

    public function addPlane(Plane $plane): self
    {
        if (!$this->planes->contains($plane)) {
            $this->planes->add($plane);
            $plane->setCategory($this);
        }

        return $this;
    }

    public function removePlane(Plane $plane): self
    {
        if ($this->planes->removeElement($plane)) {
            // set the owning side to null (unless already changed)
            if ($plane->getCategory() === $this) {
                $plane->setCategory(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->name;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getHeroImg(): ?string
    {
        return $this->hero_img;
    }

    public function setHeroImg(string $hero_img): self
    {
        $this->hero_img = $hero_img;

        return $this;
    }
}

src/Controller/PlanesCategoryController.php
<?php

namespace App\Controller;

use App\Entity\Plane;
use App\Entity\PlanesCategory;
use App\Repository\PlanesCategoryRepository;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/category', name: 'category_')]
class PlanesCategoryController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(PlanesCategoryRepository $planesCategoryRepository): Response
    {
        return $this->render('planes_category/index.html.twig', [
            'categories' => $planesCategoryRepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'list')]
    public function show(PlanesCategory $category): Response
    {
        // On récupère les appareils de la catégorie
        $planes = $category->getPlanes();

        return $this->render('planes_category/list.html.twig', [
            'planes' => $planes,
            'category' => $category
        ]);
    }
}

templates/planes_category/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Appareils
{% endblock %}

{% block body %}
	<section class="container-fluid hero-container">
		<div class="page-hero-img d-flex justify-content-center">
			<img src="{{ asset('uploads/images/main/mkh-top.webp') }}" alt="" class="img-fluid">
			<h1 class="text-center aircrafts-h1">Liste des appareils</h1>
		</div>
		{# <div class="row">
			<div class="col">
			</div>
		</div> #}
		<div class="container">
			<div class="col-12 col-lg-10 mx-auto d-flex justify-content-center">
				<p class="aircrafts-p my-3">Retrouvez dans cette section les différentes catégories d'appareils présentes dans le jeu.</p>
			</div>
		</div>
		<div class="container">
			<div class="row">
				{% for category in categories %}
					<div class="col-12 col-lg-6 mx-auto my-3">
						<div class="card h-100">
							<img src="{{ asset('uploads/images/categories/' ~ category.image) }}" class="card-img-top" alt="...">
							<div class="card-body">
								<h3 class="card-title">{{ category.name|upper }}</h3>
								<p class="card-text">Retrouvez dans cette catégorie la liste des
									{{ category.name|lower }}
									contenus dans le jeu.<br><sup>*</sup>Certains appareils peuvent être issus de contenus additionnels.</p>
								<p class="card-text">
									<small class="text-muted">Mis à jour le
										{{ category.updatedAt|format_datetime(locale='fr') }}</small>
								</p>
								<a href="{{ path('category_list', {id: category.id }) }}" class="btn btn-primary plane-btn">Voir les {{ category.name|lower }}</a>
							</div>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</section>
{% endblock %}

templates/planes_category/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ category.name }}
{% endblock %}

{% block body %}
	<section class="container-fluid hero-container">
		<div class="page-hero-img d-flex justify-content-center">
			<img src="{{ asset('uploads/images/categories/' ~ category.heroImg ) }}" alt="" class="img-fluid">
			<h1 class="text-center aircrafts-h1">{{ category.name }}</h1>
		</div>
		{# <div class="row">
			<div class="col">
			</div>
		</div> #}
			<div class="container">
				<div class="col-12 col-lg-10 mx-auto">
				<p class="aircrafts-p my-3">Retrouvez dans cette section la liste des {{ category.name|lower }} présents dans le jeu.</p>
			</div>
			</div>
		<div class="container">
			<div class="row my-5">
                {% for plane in planes %}
                    <div class="col-12 col-lg-4 mx-auto my-3">
						<div class="card h-100">
							<img src="{{ asset('uploads/images/planes/' ~ plane.image) }}" class="card-img-top" alt="...">
							<div class="card-body">
								<h3 class="card-title">{{ plane.name|upper }}</h3>
								<p class="card-text">
									<small class="text-muted">Mis à jour le
										{{ plane.updatedAt|format_datetime(locale='fr') }}</small>
								</p>
								<a href="{{ path('planes_show', {slug: plane.slug }) }}" class="btn btn-primary plane-btn">Voir le {{ plane.name }}</a>
							</div>
						</div>
					</div>
                {% endfor %}
				{# {% for category in categories %}
					<div class="col-12 col-lg-6 mx-auto my-3">
						<div class="card h-100">
							<img src="{{ asset('uploads/images/categories/' ~ category.image) }}" class="card-img-top" alt="...">
							<div class="card-body">
								<h3 class="card-title">{{ category.name|upper }}</h3>
								<p class="card-text">Retrouvez dans cette catégorie la liste des
									{{ category.name|lower }}
									contenus dans le jeu.<br><sup>*</sup>Certains appareils peuvent être issus de contenus additionnels.</p>
								<p class="card-text">
									<small class="text-muted">Mis à jour le
										{{ category.updatedAt|format_datetime(locale='fr') }}</small>
								</p>
								<a href="{{ path('category_show', {id: category.id }) }}" class="btn btn-primary">Voir les {{ category.name|lower }}</a>
							</div>
						</div>
					</div>
				{% endfor %} #}
			</div>
		</div>
	</section>
{% endblock %}